{% set name = "sunraster" %}
{% set version = "0.2.0" %}
{% set sha256 = "1b3c13e3c932bd01df8387067e153d4187fb06d09e4ce7637fa7ef34959be559" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - numpy
    - astropy >=3.1
    - ndcube >=1.3.2,<=1.9

test:
  requires:
    - pytest-astropy

  imports:
    - sunraster
    - sunraster.tests

  commands:
    - pytest --pyargs sunraster

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: A package providing instrument-agnostic data classes for manipulating solar spectrogram data.
  license_family: BSD
  dev_url: https://github.com/sunpy/sunraster
  doc_url: https://sunraster.readthedocs.io/

extra:
  recipe-maintainers:
    - DanRyanIrish
    - Cadair
